### ISSUE TITLE
Error: "The system cannot find the file specified"

### ISSUE THREAD

**Issue by DennisValente** [waf/RunOnSave#1]
Getting an error when saving a file with an extension that's configured to run a command.

**_Error Message:_**

> Exception: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    at RunOnSave.ProcessRunner.Run(CommandTemplate command, String filePath)
>    at RunOnSave.TextViewCreationListener.<>c__DisplayClass17_0.<DocumentSaved>b__0(Object _)

**_Details:_**

- Using Visual Studio 2022
- `.onsaveconfig` file and file being saved are in the same folder, which is the root folder that's open in Visual Studio
- Command used is a npm module that is installed globally
- Global npm module path is in the Path environment variable
- Can successfully run the desired command from the command-line: `markdownlint-cli2-fix C:\code\MyProject\wiki.md`

**_Config:_**

Content in file `.onsaveconfig`.

```
[*.md]
command = markdownlint-cli2-fix
arguments = {file}
```

**Comment by waf** [comment]
Hi, thanks for taking the time to report this; I appreciate the quality of the bug report!

In this case, it looks like you'll need specify `markdownlint-cli2-fix.cmd` as the command (with the `.cmd` file extension), as that's the full name of the executable.

The underlying reason for this is that we invoke the process with `UseShellExecute = false`, so users can [specify non-standard executable names](https://stackoverflow.com/questions/3434799/run-external-application-with-no-exe-extension), however this has the tradeoff that we can't rely on automatically appending `.cmd` like the shell does for us.

I'll keep this issue open for now; at the very least we should detect this exception and print some helpful text for the user. Thanks for reporting!

**Comment by waf** [comment]
I've opened a PR that provides a better error message. Please let me know if specifying the .cmd file extension works for you; if it does then I'll merge the PR and push a new release.  Thanks!

**Comment by DennisValente** [comment]
@waf appending the `.cmd` to the command, did indeed work for me! Thanks for looking into this so fast and providing the details as to the cause. Adding a better error message is a great idea! May I suggest there also be some mention in the `README.md`?

**Comment by waf** [comment]
Thanks! I just pushed a new version, with the better error message and an update to the README.
