### ISSUE TITLE
Not working with latest version of VS22

### ISSUE THREAD

**Issue by Myndale** [waf/RunOnSave#10]
This doesn't seem to be working with the latest version of VS22 (17.2.0). The steps to reproduce are as follows:

- Create a new Console application
- Add a file to the project called "test.js" with a single line of JavaScript code e.g.:
```
    alert("Hello World!");
````
- Add  a .onsaveconfig file to the project with the following contents:
```
    [*.js]
    command = \Dev\ConsoleApp1\ConsoleApp1\my_batch_file.bat
```
- Finally, add a batch file to the \Dev\ConsoleApp1\ConsoleApp1 folder called "my_batch_file.bat" with a single command:
```
    echo "Hello World!" > foo.txt
```

Editing test.js and saving it never causes the foo.txt file to appear, whereas running my_batch_file.bat manually does.

I've restarted VS, and also tested with other project types and extensions. Unless there's something I've missed, nothing seems to be working.

**Comment by lflender** [comment]
Cannot make it work either with VS17.5.

Still no answer, so this extension is dead?

**Comment by Gambero81** [comment]
Hi @waf , can you update the extension for visual studio 2022?

Thanks

**Comment by Gambero81** [comment]
it work now!

**Comment by waf** [comment]
This is now released with support for the latest version of Visual Studio. 🎉
