### ISSUE TITLE
Handle relative path for command

### ISSUE THREAD

**Issue by Gambero81** [waf/RunOnSave#11]
It would be glad to allow relative path on command property.
Ex.

`command=..\myApp.exe`

or eventually:

`command={solution_directory}\myApp.exe`

so the project source files can be placed on different paths.

Thanks

**Comment by waf** [comment]
Hi, thanks for the feedback. I've just uploaded a new version of the extension (v1.5) that allows `{solution_directory}` to be used in the `command` field. Hope this works OK for you!

If you run into any issues feel free to re-open this issue.
