### ISSUE TITLE
Wrong value for solution_directory argument

### ISSUE THREAD

**Issue by Gambero81** [waf/RunOnSave#12]
Sometime occurs that `{solution_directory}` argument value is wrong.

For example, if my solution is `C:\MySolution` it return `C:\MySolution\MyProject`

What's wrong?

NB. i have 2 .onsaveconfig files, and they are placed inside project path (ex. `C:\MySolution\MyProject1\.onsaveconfig` and  `C:\MySolution\MyProject2\.onsaveconfig`

**Comment by waf** [comment]
Hmm, that's interesting, I'm not sure what is causing that.

Internally, the extension just used the process working directory of Visual Studio, which is the solution directory. But possibly this could be different if Visual Studio is launched in different ways.

I've just released version 1.5 that actually uses the Visual Studio SDK to determine the solution directory, which should be more dependable.

If you run into any issues feel free to re-open this issue.
