### ISSUE TITLE
Error when the working_directory has a white space.

### ISSUE THREAD

**Issue by SSorinC** [waf/RunOnSave#5]
There is a problem when the working_directory path has a white space.

Example: C:\Folder1\Name1 Name2\Folder2

The output will display only the first part "C:\Folder1\Name1"
There is a way to handle this situation?

Thank you!

**Comment by waf** [comment]
Hi @SSorinC, my apologies for completely missing this issue! I've been unable to recreate this issue. For example, I'm using the following `.onsaveconfig` file with a space in the `working_directory` value:

```ini
[*.cs]
command = dotnet
arguments = csharpier "{file}"
working_directory = C:\Projects - Personal\MySolution\MyProject
```

Could you please provide a sample onsaveconfig file that shows the issue?

**Comment by waf** [comment]
Closing as can-not-reproduce.
