### ISSUE TITLE
Skipping formatting -- file not changed

### ISSUE THREAD

**Issue by Gitii** [waf/RunOnSave#6]
Hi,

I really like this extension, it's easy to use and to extend.
So far, I have only noticed one problem - sometimes changed files don't get touched by RunOnSave, but instead `Skipping formatting -- file not changed` gets printed. I have Resharper installed, which also applies some refactoring on save.
Closing the file and opening it again solves the issue, until it stops "working" (after some time).

I think that Resharper somehow messes up the has-file-changed-check.

As a workaround, is it possible to add an option to either skip the check or explicitly force a command execution (using a hotkey or on strl+s)?

Thanks!

**Comment by waf** [comment]
Hi @Gitii, thanks for raising this issue, and for the kind words.

Yeah, I've experimented with a couple different ways of detecting whether or not a file has changed, and they all have tradeoffs. I think these tradeoffs will be different for everyone, so it makes sense to allow disabling this behavior altogether.

I've just pushed a branch (PR #7) that adds a new `always_run` configuration option; in your case you'd want to set `always_run = true` in your `.onsaveconfig` file. 

I've attached a release build below that includes the new feature. As I don't use Resharper, could you please give try it and let me know if it fixes the issue you're encountering? Thanks!

[RunOnSave.zip (unzip for a vsix file, double click that vsix file to install it)](https://github.com/waf/RunOnSave/files/8404795/RunOnSave.zip)

**Comment by Gitii** [comment]
@waf Thanks, I will try it out! Sorry for my slow response time, I had not enough free time during the week 😒

**Comment by Gitii** [comment]
@waf I can confirm that #7 works as intended.
